### ISSUE TITLE
Support requesting multiple permissions at the same time.

### ISSUE THREAD

**Issue by pedrovgs** [Karumi/Dexter#1]
With the current Dexter implementation we are only allowed to request one permission at a time. We have to add a new feature to the library to be able to request multiple permissions with just one call to the library.

**Comment by Serchinastico** [comment]
We need to think how to inform the library client of the different states for each permission requested, keep in mind that the user can grant some of them and deny the rest.
I'll play with Android to see how multiple permission requests are displayed to the user and think of an approach based on that.

**Comment by Shusshu** [comment]
Yes, this is important as for example to use the camera you need CAMERA & RECORD_AUDIO permissions

**Comment by Serchinastico** [comment]
Released in 2.0.0!
