### ISSUE TITLE
Follow git-flow for the repo

### ISSUE THREAD

**Issue by blipinsk** [Karumi/Dexter#10]
Hi guys!

Would it be possible for you to follow git-flow for the repo?
It can be a bit confusing, if you've got not-yet-released features on your `master` branch.
E.g. I wanted to peek into your `sample` module, and saw completely different `PermissionListener` being used. And I needed to perform a small investigation to see if I was doing something wrong or if it was just something not yet released.

Thanks

**Comment by Serchinastico** [comment]
Hi @blipinsk 

We have discussed this internally and we've got to the conclusion of keeping the repository as simple as possible. We will use master for small non-breaking changes/fixes and create other branches for bigger features (like adding support for perma-denied permissions & multirequest). The fact that the repository is not following this rule right now is just a mistake we are trying to fix. We are sorry for the inconvenience :(

Thanks for your feedback though, we will think about it for bigger projects.

**Comment by blipinsk** [comment]
Fair enough :smirk: , thanks for the response.

Great job on the library by the way, relatively simple, but highly useful. :+1: 
I'm hoping you'll manage to implement the callback on the perma-denied permissions into the library. It would be the icing on the cake.
