### ISSUE TITLE
Manifest.permission.WRITE_SETTINGS does not work

### ISSUE THREAD

**Issue by JackLauu** [Karumi/Dexter#102]
Everytime I use Dexter.checkPermission(new PermissionListener(), Manifest.permission.WRITE_SETTINGS) to check the write settings permission, it will enter onPermissionDenied, even if I turn on the write settings permission. I don't know why.

**Comment by Serchinastico** [comment]
Hi @JackLauu,

We don't handle `WRITE_SETTINGS` and `SYSTEM_ALERT_WINDOW` as they behave very differently from the other permissions. I'm afraid if you want to request those permissions you'll have to do it the usual way, without Dexter.

See https://developer.android.com/guide/topics/permissions/requesting.html, https://developer.android.com/reference/android/Manifest.permission.html#SYSTEM_ALERT_WINDOW and https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SETTINGS to learn how to request them.

Thanks for reporting.

**Comment by JackLauu** [comment]
That's ok, thank you.
