### ISSUE TITLE
Permissions dialog not restored correctly when pressing home

### ISSUE THREAD

**Issue by edualonso** [Karumi/Dexter#113]
Android's permission dialog is not restored if you press home while showing the permissions dialog and return to the activity that was showing it.

### Actual behaviour
A DexterError.REQUEST_ONGOING is thrown. Obviously, this is correct, as I never allowed nor denied the permission, but I'm unable to continue the permission by using Dexter.withActivity(activity).continueRequestingPendingPermissions(permissionListener)

### Expected behaviour
It should restore the dialog after  calling Dexter.withActivity(activity).continueRequestingPendingPermissions(permissionListener).

### Steps to reproduce
Request a permission
Press home when the allow/deny dialog is shown
Re-open the activity that showed the permissions dialog

### Version of the library
3.0.2

**Comment by pedrovgs** [comment]
Maybe we should remove this feature. Votes?

**Comment by edualonso** [comment]
With "remove this feature" you mean drop existing permission requests all along and allow to request fresh permissions when this occurs? If so, then I give you a +1 too.

**Comment by pedrovgs** [comment]
Yeap.

**Comment by pedrovgs** [comment]
The feature is too complex, the implementation is difficult and does not add value at all.

**Comment by edualonso** [comment]
Cool, looking forward to request new permissions without being blocked by previous requests.

ps. gracias por responder cagando leches ;-)

**Comment by pedrovgs** [comment]
xD no problem @edualonso. If we won the YES in this vote and you want to collaborate implement this feature it could be great :)

**Comment by mikejeep** [comment]
I came on here specifically because I was experiencing this same issue. Certainly in favor of this resolution, although I'm sorry I am a novice and wouldn't be much help implementing it.

**Comment by Serchinastico** [comment]
We will remove the feature, people using Dexter is already doing something like asking for the permissions in the activity start up just in case so... :+1:

**Comment by pedrovgs** [comment]
@edualonso I've sent a PR. Can you check the behaviour is the one you expect.

**Comment by Serchinastico** [comment]
Version 4.0.0 has now been released!

**Comment by stoefln** [comment]
Exactly this is happening for me in version 5.0.0 on wear os!

**Comment by felipe-silvestre-morais** [comment]
This is still happening in version 5.0.0
