### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mhdtouban** [Karumi/Dexter#117]
### Expected behaviour
no memory leaks

### Actual behaviour
static Dexter.instance references DexterInstance.listener

### Steps to reproduce
      Dexter.withActivity(getActivity())
                    .withPermission(Manifest.permission.READ_EXTERNAL_STORAGE)
                    .withListener(compositePermissionListener).check();
### Version of the library
3.0.2

**Comment by Serchinastico** [comment]
Hi @mhdtouban 

This has been already reported in #94 but we can't do anything to avoid a false positive in LeakCanary as we are effectively holding a reference to the calling activity until the permission is accepted/denied.

If you think this has nothing to do with your issue and still think there is a bug in Dexter, don't hesitate to reopen this issue and we will take another look to the matter.

Thanks for reporting!
