### ISSUE TITLE
"All com.android.support libraries must use the exact same version specification"

### ISSUE THREAD

**Issue by omaflak** [Karumi/Dexter#121]
Hello, thanks for your great library !

I get the error in my build.gradle on this line `compile 'com.android.support:appcompat-v7:25.2.0'` :

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes).

I can still run the project, but the compile line is underlined in red and it annoys me a bit ...

Do you have any suggestion ? Thanks !

**Comment by Aiden-Ziegelaar** [comment]
This is because the library has not been updated to use the new support libraries, presently it is using:
* com.android.support:appcompat-v7:25.1.0
* com.android.support:design:25.1.0

The fix for now would be to use 25.1.0 libraries for your project, or to download and build the project yourself using the new libraries.

**Comment by Serchinastico** [comment]
Hello, fellow programmers!

Yes, as @Aiden-Ziegelaar comments the reason for the warning is that Dexter is using an _old_ version of the appcompat library. We are planning to release v4.0.0 today, we will make sure that version is completely updated. However, if you don't feel like updating there you can always exclude the appcompat dependency from Dexter to use your own. To do so, you have to load Dexter in your gradle file as follows:

```
testCompile('com.karumi:dexter:4.0.0') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'design'
}
```

Remember that you should provide those dependencies by yourself or the project won't even compile.

Thanks for reporting and helping us to improve!

**Comment by Serchinastico** [comment]
I'm closing this issue for now, we will release the updated version (#122)

**Comment by omaflak** [comment]
Great ! I'm looking forward to see the new version !

**Comment by mackongo** [comment]
Was this solved?

**Comment by omaflak** [comment]
Yes, you have to use version 4.0.0 of the library.

**Comment by mackongo** [comment]
I still experience an error after the changes.

**Comment by sudheerkumarnokku** [comment]
compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    compile 'com.google.firebase:firebase-messaging:11.0.4'
    compile 'com.google.firebase:firebase-auth:11.0.4'

**Comment by sudheerkumarnokku** [comment]
compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    compile 'com.google.firebase:firebase-messaging:11.0.4'
    compile 'com.google.firebase:firebase-auth:11.0.4'
 is correct or not
tell me

**Comment by am9072** [comment]
For those who still getting some error is because of android-support conflicting versions
Solution :
https://youtu.be/UDLqFbat7n0

This will solve your problem.

**Comment by mgpx** [comment]
> For those who still getting some error is because of android-support conflicting versions
> Solution :
> https://youtu.be/UDLqFbat7n0
> 
> This will solve your problem.


Thank you for sharing, it worked for me too.

**Comment by PatelAshish11** [comment]
Go to project/.idea/libraries folder on your file system and see which libraries are different.
You will have to manually include these libraries with the same version in your build.gradle file.
Then, sync your project.
E.g.:

Ex [Here](https://icetutor.com/question/all-com-android-support-libraries-must-use-the-exact-same-version-specification/)

**Comment by AkashGalani** [comment]
Go to project/.idea/libraries folder on your file system and see which libraries are different.
You will have to manually include these libraries with the same version in your build.gradle file.
Then, sync your project.

Example [Here](https://icetutor.com/question/all-com-android-support-libraries-must-use-the-exact-same-version-specification/)
