### ISSUE TITLE
Remove unnecessary and unused ci android component

### ISSUE THREAD

**Issue by albodelu** [Karumi/Dexter#131]
### Expected behaviour
CI build without the unnecessary android component like [here](https://github.com/Karumi/Dexter/pull/130)

### Actual behaviour
CI build tries to download the unused android component and shows a warning about it

### Steps to reproduce
Check any log like [this](https://travis-ci.org/Karumi/Dexter/builds/208518631#L933)

### Version of the library
Any

**Comment by Serchinastico** [comment]
:1st_place_medal:
