### ISSUE TITLE
Create a companion library with default implementations

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Dexter#134]
We have a lot of reports to add functionality to the default snackbar and dialog implementations that we don't really want to mix with Dexter itself. Maybe it's a good idea to create a companion library called something like `dexter-addons`, `dexter-widgets` or `dexter-extra` to move those implementations there.

Does it sound ok? @pedrovgs @flipper83

**Comment by pedrovgs** [comment]
I'd not go for a ``dexter-addons`` artifact. This code is being used by our users as part of the production code when it's just an example. I'd keep it as is or just move the code to the example application.

**Comment by pedrovgs** [comment]
What do you think @flipper83 @fjfdeztoro ?

**Comment by Serchinastico** [comment]
We will keep those classes in Dexter and improve them if people send us PRs to better configure them. As you said, they are in the main project and people is using them as part of Dexter in their code so.

Thanks for your help!
