### ISSUE TITLE
Con not Using Dexter from Jcenter Repository (in the compile 'com.karumi:dexter:4.1.0' version)

### ISSUE THREAD

**Issue by Mahdihp** [Karumi/Dexter#146]
![image](https://cloud.githubusercontent.com/assets/6378625/25844229/06462cbe-34bf-11e7-8add-bd9338586cb7.png)

**Comment by pedrovgs** [comment]
Hi @Mahdihp we deploy our artifacts to [Maven Central](https://mvnrepository.com/artifact/com.karumi/dexter)

You can add this configuration to your ``build.gradle`` file if you need to consume any lib from MavenCentral

```groovy 
repositories {
    mavenCentral()
}
```

**Comment by Mahdihp** [comment]
note working mavenCentral(). me Using jcenter() (using 10 library of jcenter())

**Comment by Serchinastico** [comment]
We don't support jcenter. Anyways, you can still use maven central AND jcenter, there is generally no problem in that.

**Comment by Mahdihp** [comment]
Ohhhhhhhhh NOOOOOOOOOOOO

**Comment by Serchinastico** [comment]
![https://media.giphy.com/media/xHwqspaBmfUMU/giphy.gif](https://media.giphy.com/media/xHwqspaBmfUMU/giphy.gif)
