### ISSUE TITLE
Provide example on how to handle device rotation.

### ISSUE THREAD

**Issue by greysonp** [Karumi/Dexter#15]
When you request a permission, Dexter makes note that a permission request is outstanding. If I previously denied a permission, I'll get the callback ```showPermissionRationale(PermissionToken)```. We're supposed to use this to continue our permission request with ```PermissionToken.continuePermissionRequest()``` or cancel it with ```PermissionToken.cancelPermissionRequest()```. However, if I choose to show an ```AlertDialog``` (as is done in the ```SampleActivity```, the user could rotate the device, leading to me losing access to my token and being unable to cancel or continue the request.

This would lead to the crasher described in #14, which was fixed by locking the orientation of the sample app.

What I'd like to see is an example on how you suggest we recover our state after a device rotation. Specifically, what is your suggested way to persist the ```PermissionToken```? 

It'd be great if this were in the sample app.

**Comment by pedrovgs** [comment]
Thanks @greysonp I'm working on it :)

**Comment by Serchinastico** [comment]
Version 2.1.0 contains methods and an example of how to handle this with the library. Thank you all for your contribution!
