### ISSUE TITLE
The dexter activity does not persist across device rotations

### ISSUE THREAD

**Issue by greatjack1** [Karumi/Dexter#168]
### Expected behaviour
If the device is rotated when the permission dialog is shown, then it should still show the dialog

### Actual behaviour
when the device is rotated it stops showing the dialog

**Comment by pedrovgs** [comment]
@greatjack1 could you provide some extra information? We need to know the library version you are using and also the  Android OS version

**Comment by pedrovgs** [comment]
Duplicated by #276
