### ISSUE TITLE
SnackbarOnDeniedPermissionListener.Builder.with requires ViewGroup

### ISSUE THREAD

**Issue by stefan-nsk** [Karumi/Dexter#169]
### Expected behaviour

```java
SnackbarOnDeniedPermissionListener.Builder.with(
    findViewById(R.id.some_view), R.string.some_text)
```

### Actual behaviour

```java
SnackbarOnDeniedPermissionListener.Builder.with(
    (ViewGroup) findViewById(R.id.some_view), R.string.some_text)
```

### Steps to reproduce

Try to create `SnackbarOnDeniedPermissionListener` using static method of builder.

### Version of the library

**4.1.0**

**Comment by pedrovgs** [comment]
Hi @stefan-nsk I guess this is not a bug xD The snack bar component requires a ``ViewGroup`` instance. I'm closing this issue, sorry. If you want to avoid the downcasting you can use a library like [butterknife](https://github.com/JakeWharton/butterknife) so the casting is performed by the library and if the casting fails your app will crash.

**Comment by pedrovgs** [comment]
My bad, the library accepts a view and in ``Snackbar:135`` is going to find the view parent. We could change the code to accept ``View`` instead of ``ViewGroup`` as param. As this is not a major feature we will wait for a collaborator PR 😃 if you don't mind.

**Comment by stefan-nsk** [comment]
You are welcome: #171.

**Comment by pedrovgs** [comment]
uooo thanks!
