### ISSUE TITLE
it leaks memory with simple usage case.

### ISSUE THREAD

**Issue by aalap03** [Karumi/Dexter#175]
I am using dexter with this scenario in my fragment and it leaks a lot of memory gradually around 10MBs. Is there any solution or work around to this ?

    Dexter.withActivity(context)
                    .withPermission(Manifest.permission.ACCESS_FINE_LOCATION)
                    .withListener(new PermissionListener() {
                        @Override
                        public void onPermissionGranted(PermissionGrantedResponse response) {

                            if (locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER) && mGoogleApiClient != null && mGoogleApiClient.isConnected()) {

                                if (Build.VERSION.SDK_INT >= 23) {
                                    if (checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED)

                                } else {
                                   
                                }

                                Utils.toggleLoader(loadingFrame, true);

                            } else {
                                if (!locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER))
                                    openGPSDialog();
                            }

                        }

                        @Override
                        public void onPermissionDenied(PermissionDeniedResponse response) {
                           
                            Toasty.info(context, getString(R.string.toast_perm_denied_location)).show();
                        }

                        @Override
                        public void onPermissionRationaleShouldBeShown(PermissionRequest permission, PermissionToken token) {
                            token.continuePermissionRequest();
                        }
                    })
                    .check();

**Comment by Serchinastico** [comment]
Hi @aalap03,

How are you verifying there is a memory leak? Have you verified it's effectively in Dexter? What version of the library are you using?

Next time, please follow the issue template or we will close it right away.

**Comment by aalap03** [comment]
Apologies for incomplete information, so I am verifying with LeakCanary, and the version is 4.1.0. This is the latest screen shots I have from leak canary, I deleted all the leaks so I have lost the leak of 10Mb which I mentioned in the title. 



![screenshot_20170817-101818](https://user-images.githubusercontent.com/12421219/29417020-d6a57422-8335-11e7-83b9-236061434370.png)

**Comment by aalap03** [comment]
Closing it as decided not to use library and go with android implementation.

**Comment by oa-azab** [comment]
got same result from leakcanary on version 4.1.0
