### ISSUE TITLE
Large dependencies

### ISSUE THREAD

**Issue by mohamad-amin** [Karumi/Dexter#178]
As [in this page](http://www.methodscount.com/?lib=com.karumi%3Adexter%3A4.1.0) this library has many dependencies that aren't used in many applications and somehow adds some overhead and extra method count, I know proguard will try to take care of this but I think it doesn't completely erase all unneeded dependencies.
Is there any way of removing some of these dependencies or at least creating some modules so that we just include the part we need?
Thanks.

**Comment by Serchinastico** [comment]
Hi @mohamad-amin 

The only two dependencies we have right now in the library are `com.android.support:design` and `com.android.support:appcompat-v7`. These are libraries that most of the projects should have already in their apps. The only way to reduce the method count would be to move the Snackbar implementation to a companion library but given the size of the project I'd rather not go that way.

I'd recommend you forking the project and removing the libraries yourself.
