### ISSUE TITLE
Permissions group

### ISSUE THREAD

**Issue by s1mar** [Karumi/Dexter#179]
Would it work if I simply supply the Permissions group to .withPermission() and if yes,then which listener would be used,Multiple or single one ?

**Comment by Serchinastico** [comment]
Hi @s1mar 

If you use `withPermission` then you should be passing one and only one permission, the API won't let you pass anything else. In that case you can only provide a regular `PermissionListener`. If you use `withPermissions` then you are forced to use a `MultiplePermissionsListener`. The API is using a builder that won't let you make the wrong choice so it should be rather easy.

Feel free to reopen the issue if we didn't answer your question.
Thanks!
