### ISSUE TITLE
error in build.gradle

### ISSUE THREAD

**Issue by salmansidd17** [Karumi/Dexter#180]
### Expected behavior
it was supposed to be successfully compiled when it put 
`compile 'com.karumi:dexter:4.1.0'`
in the dependencies.

### Actual behavior
i am using `'com.android.support:appcompat-v7:25.3.1'` and dexter:4.1.0 seems to be incompatible with gradle 25.3.1.

### Steps to reproduce
use library with these versions
```
compile 'com.android.support:appcompat-v7:25.3.1'
compile 'com.karumi:dexter:4.1.0'
```

### Version of the library
dexter:4.1.0

**Comment by Serchinastico** [comment]
Hi @salmansidd17 

We have a pending release (will be `4.2.0`) that is using `com.android.support:appcompat-v7:25.3.1`. However, if you need it right now, I'd suggest you to exclude the appcompat dependency from dexter by using this configuration:

```groovy
compile 'com.karumi:dexter:4.1.0' {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

I haven't tested it myself but it should work just fine.

**Comment by salmansidd17** [comment]
Hi @Serchinastico ,
I got it to work by downloading the library myself and recompiling it with the latest appcompact version. I'll try your method too. Hope it'll work fine. 
Thank you :)

**Comment by yussefbens** [comment]
for those who still research for solution with this issue.. try to implement android.design
`implementation 'com.android.support:design:27.1.1'`
I tried the solution suggested by @Serchinastico by it not seems working then I download the lib and install it manually in my project and I found the error in the Snackbar where you should already have android.support.design to use it.

**Comment by josephsarz** [comment]
> `compile('com.karumi:dexter:5.0.0') { exclude group: 'com.android.support' }`

This solved my issue. Thanks @leigo
