### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by sudheerkumarnokku** [Karumi/Dexter#191]
my errors
Failed to resolve: com.google.firebase:firebase-messaging:11.0.4
Failed to resolve:com.google.firebase:firebase-core:11.0.4
  Failed to resolve : com.google.firebase:firebase-auth:11.0.4
plz help me this is my first app

**Comment by sudheerkumarnokku** [comment]
my errors
Failed to resolve: com.google.firebase:firebase-messaging:11.0.4
Failed to resolve:com.google.firebase:firebase-core:11.0.4
Failed to resolve : com.google.firebase:firebase-auth:11.0.4
plz help me this is my first app

**Comment by Serchinastico** [comment]
Hi,

We have some guidelines to open an issue, please follow them so that we can better help you.
