### ISSUE TITLE
Add action to go to app settings in Snackbar

### ISSUE THREAD

**Issue by aconsuegra** [Karumi/Dexter#2]
The Snackbar shown after a permission is denied could show an action to enable the permission in app settings

**Comment by pedrovgs** [comment]
As we've talked, we will wait for your PR @aconsuegra :) Thanks!

**Comment by pedrovgs** [comment]
@Serchinastico this is already implemented, isn't it?

**Comment by aconsuegra** [comment]
Ouch, it seems it is supported in the API, but I didn't see it in the .gif 😥

**Comment by Serchinastico** [comment]
Yup, I'll update the gif ASAP, it was a last minute feature :)
