### ISSUE TITLE
Conflict with com.android.support:support-core-utils:26.1.0

### ISSUE THREAD

**Issue by jangrewe** [Karumi/Dexter#201]
### Expected behaviour
I'm using `com.android.support:support-core-utils:26.1.0`, but it looks like Dexter still uses `com.android.support:animated-vector-drawable:25.3.1`, which creates a conflict in Android Studio.

### Version of the library

4.2.0

**Comment by stefanborne** [comment]
I had a problem building project with the newest support library (27.1.0), so I had to include these:

configurations.all {
    resolutionStrategy.force "com.android.support:animated-vector-drawable:$support_version"
    resolutionStrategy.force "com.android.support:design:$support_version"
}

Now everything works well and there is no conflict anymore.

**Comment by jangrewe** [comment]
Thanks, that's a very handy option!

**Comment by Serchinastico** [comment]
We are updating those libraries on the go so you can either wait for an updated release or force a version yourself in your gradle version. Thanks for reporting
