### ISSUE TITLE
All com.android.support libraries must use the exact same version specification

### ISSUE THREAD

**Issue by yigitserin** [Karumi/Dexter#217]
I am getting this error on my gradle file after updating to build tools 28.

**Comment by Serchinastico** [comment]
I think #201 or #121 already addressed this issue.

Please, feel free to reopen it if you find your problem persists.

**Comment by AkashGalani** [comment]
Go to project/.idea/libraries folder on your file system and see which libraries are different.
You will have to manually include these libraries with the same version in your build.gradle file.
Then, sync your project.

Example [Here](https://icetutor.com/question/all-com-android-support-libraries-must-use-the-exact-same-version-specification/)
