### ISSUE TITLE
Check does not a second time

### ISSUE THREAD

**Issue by AlexVPerl** [Karumi/Dexter#222]
### Expected behaviour
Check & listener methods should run as many times as it is called.

### Actual behaviour
Check & listener methods do not run 2nd time they are called.

### Steps to reproduce
Using listener methods to redirect to another activity to show rationale. Calling .check on 2nd time does nothing.

### Version of the library
Latest 5.0

**Comment by Ynnck123** [comment]
I also face this issue, any updates on this?
