### ISSUE TITLE
Permissions dialog not working in fragment

### ISSUE THREAD

**Issue by sathishmscict** [Karumi/Dexter#227]
### Steps to reproduce
MainActivity permission allow then replace a fragment in activity. From fragment location permission checked with Dexter permission allow dialogue not appeared. 

    Dexter.withActivity(getActivity())
                        .withPermissions(
                                Manifest.permission.ACCESS_COARSE_LOCATION,
                                Manifest.permission.ACCESS_FINE_LOCATION
                        ).withListener(new MultiplePermissionsListener() {
                    @Override
                    public void onPermissionsChecked(MultiplePermissionsReport report) {
                        /* ... */

                    }

                    @Override
                    public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {
                        /* ... */
                        // token.continuePermissionRequest();
                    }
                }).check();

**Comment by Papashkin** [comment]
@sathishmscict I'm using this library in fragments and seems it works ok.
I use Dexter like the following code:
` vButtonCamera.setOnClickListener {
            Dexter.withActivity(this.activity)
                    .withPermission(Manifest.permission.CAMERA)
                    .withListener(permissionListener)
                    .check()
}`

I'm just using Kotlin instead Java, but `this.activity` in Kotlin is the same as `this.getActivity()` in Java.

**Comment by PalakSDarji** [comment]
happens to me too..

**Comment by krahul08** [comment]
Expected behaviour
Once denied it will  ask permissions  again and again  until permanently  denied.
Actual behaviour
It is not asking permissions  once denied .
Steps to reproduce
MainActivity permission allow then replace a fragment in activity. From fragment location permission checked with Dexter permission allow dialogue not appeared.

Dexter.withActivity(getActivity())
                .withPermissions(
                        Manifest.permission.READ_EXTERNAL_STORAGE,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE
                ).withListener(new MultiplePermissionsListener() {
            @Override public void onPermissionsChecked(MultiplePermissionsReport report) {

                if (report.areAllPermissionsGranted()) {
                    Toast.makeText(context, "hello", Toast.LENGTH_SHORT).show();
                }

                // check for permanent denial of any permission
                if (report.isAnyPermissionPermanentlyDenied()) {
                    // show alert dialog navigating to Settings
                    showSettingsDialog();
                }

            }
            @Override public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {
                   token.continuePermissionRequest();
            }
        }).withErrorListener(new PermissionRequestErrorListener() {
            @Override
            public void onError(DexterError error) {
                Log.d("Debuger",error.toString());

            }
        }).onSameThread().check();

Version of the library   implementation 'com.karumi:dexter:5.0.0'

I’m  using this in fragment.

**Comment by pedrovgs** [comment]
@sathishmscict @PalakSDarji can you please fill the issue template properly? We need to know the expected behavior, the behavior you are facing, and the version of the library you are using to be able to understand what's going on. If you could also create an example project on GitHub reproducing the error, that'd be awesome 😃

**Comment by chihung93** [comment]
@pedrovgs : happens to me too....Its happen on Samsung devices

**Comment by pedrovgs** [comment]
@chihung93 could you please upload any android project reproducing the issue in a simple example? Just a simple empty app where you can reproduce the issue. I'm trying to reproduce it in a new project, but there must be something I'm missing.

**Comment by chihung93** [comment]
@chihung93 : nope, I don't have time to do this anymore, Some device don't get this issue, but Samsung always get this problem....
It's only happening on Fragment and using Samsung device.

**Comment by chihung93** [comment]
My code is the same @sathishmscict , but I have this line token.continuePermissionRequest();


```
Dexter.withActivity(getActivity())
                    .withPermissions(
                            Manifest.permission.ACCESS_COARSE_LOCATION,
                            Manifest.permission.ACCESS_FINE_LOCATION
                    ).withListener(new MultiplePermissionsListener() {
                @Override
                public void onPermissionsChecked(MultiplePermissionsReport report) {
                    /* ... */

                }

                @Override
                public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {
                    /* ... */
                    token.continuePermissionRequest();
                }
            }).check();
```

**Comment by pedrovgs** [comment]
Only happening on Samsung devices @chihung93 ? I don't have any Samsung device to fix this issue at all. Could some external collaborators help us with this? We should first check how to reproduce the error.

**Comment by mskn73** [comment]
I am using dexter in a fragment and it is working in Galaxy S8 (G950F) with android 9. I am not sure if it fails in older Samsung devices. Also I tested with simple and multiple permissions.

**Comment by kojofosu** [comment]
It works in my fragment class too...using a samsung s8 device

**Comment by pedrovgs** [comment]
As we have two confirmations from different years of the library working in Samsung devices I'm closing the issue. Thank you all for your comments and help 😃

**Comment by Marsad-Ch** [comment]
I'm facing the same issue permission dialog appears in activity but not working in fragment

Here is the code which I'm using in fragment

```
Dexter.withContext(getActivity())
                        .withPermissions(
                                Manifest.permission.READ_EXTERNAL_STORAGE,
                                Manifest.permission.WRITE_EXTERNAL_STORAGE
                        ).withListener(new MultiplePermissionsListener() {
                    @Override
                    public void onPermissionsChecked(MultiplePermissionsReport report) {
                        if (report.areAllPermissionsGranted()) {
                            selectImage();
                        } else {
                            Toast.makeText(getContext(), "Please allow permissions", Toast.LENGTH_SHORT).show();
                        }
                    }

                    @Override
                    public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {/* ... */}
                }).check();
```

when I click on button instead of showing permission dialog 

the else statement runs and toast message shows

```
if (report.areAllPermissionsGranted()) {
       selectImage();
  } else {
       Toast.makeText(getContext(), "Please allow permissions", Toast.LENGTH_SHORT).show();
 }
```

**Comment by pisxid** [comment]
> As we have two confirmations from different years of the library working in Samsung devices I'm closing the issue. Thank you all for your comments and help 😃

If it helps, for some reason you need to delete, recompile and install the app.
