### ISSUE TITLE
still getting Erroe in library

### ISSUE THREAD

**Issue by ppda1996** [Karumi/Dexter#230]
### Actual behaviour
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'  //still got error of com.android.support library must use the exact same version specification after adding dexter library and syncing.
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.karumi:dexter:5.0.0'
}

### Version of the library

com.karumi:dexter:5.0.0

**Comment by mainuddinprodan** [comment]
Network do not working

**Comment by pedrovgs** [comment]
Could you please describe the error properly?
