### ISSUE TITLE
Fragment is recreated after permission confirming

### ISSUE THREAD

**Issue by Papashkin** [Karumi/Dexter#231]
I implemented this library to my project and now I'm trying to use it in fragment to get camera permission.
### Expected behaviour
After confirming I want to start camera fragment withaout application re-creation.

### Actual behaviour
After confirming I return to last state of application.
I tried to override the `onRequestPermissionsResult` method, but in this method I receive the GRANTED value (i.e. 0) in any cases (independently I click on `cancel` or `ok` button in permission dialog).

### Version of the library
last version (5.0.0)

**Comment by NimaaZx** [comment]
@Papashkin Hi, 
Can you resolve this problem ?

**Comment by nguyennh-0786** [comment]
Maybe add a small delay time before doing something.

**Comment by pedrovgs** [comment]
@Papashkin can you create a small project reproducing this issue so we can use it as a playground to see what's going on? Thank you in advance 😃

**Comment by c0dehunter** [comment]
I'm having the same problem. In Fragment, I use Dexter to ask for permissions, and for test I don't do anything in onPermissionGranted.  Still, the fragment closes.

**Comment by Papashkin** [comment]
Hello!
This issue is no longer relevant anymore.
You can close this issue.
