### ISSUE TITLE
Application stuck when requesting ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by choryuidentify** [Karumi/Dexter#240]
### Expected behaviour
Show permission is granted or not granted

### Actual behaviour
Stuck on there
tested on Android Q Emulator

### Steps to reproduce
Permission -> Location -> Choose 'Allow only while using app'
then, write code 

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            Dexter.withActivity(this)
                    .withPermission(Manifest.permission.ACCESS_BACKGROUND_LOCATION)
                    .withListener(object : PermissionListener{
                        override fun onPermissionRationaleShouldBeShown(permission: PermissionRequest?, token: PermissionToken?) {
                            Log.d("debug", "onPermissionRationaleShouldBeShown")
                        }

                        override fun onPermissionDenied(response: PermissionDeniedResponse?) {
                            Log.d("debug", "denied")
                        }

                        override fun onPermissionGranted(response: PermissionGrantedResponse?) {
                            Log.d("debug", "granted")
                        }
                    }).check()
        }

and run, choose 'Keep while-in-use access' or 'Keep and don't ask again', It stuck.
If choose 'Allow all time', It stuck too but restart app, it will execute onPermissionGranted block

### Version of the library
6.0.0

**Comment by AlexDundar** [comment]
I have the same problem. Is there any solution?

**Comment by pedrovgs** [comment]
Hi @choryuidentify @AlexDundar  I've been testing the issue you reported and it's not related to Dexter but the way you ask for the permission. When using the background location permission you have to request the fine location or coarse location permission too. However, your code is only requesting the background ones. If you use this code you'll see how the app is working now:

```kotlin
Dexter.withActivity(this)
            .withPermissions(Manifest.permission.ACCESS_BACKGROUND_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION)
            .withListener(object : MultiplePermissionsListener {
                override fun onPermissionsChecked(report: MultiplePermissionsReport?) {
                    
                }

                override fun onPermissionRationaleShouldBeShown(
                    permissions: MutableList<PermissionRequest>?,
                    token: PermissionToken?
                ) {
                    token?.continuePermissionRequest()
                    
                }
                
            }).check()
```

Remember to declare these permissions in the manifest. 

Here you can find two useful resources related to this topic:

* [Official Android documentation.](https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_BACKGROUND_LOCATION)

![Screenshot 2019-11-08 at 12 49 46](https://user-images.githubusercontent.com/4030704/68474640-44880880-0226-11ea-8713-d6415f166c4e.png)

* [An awesome blog post about permissions in Android Q by Joe Birch](https://medium.com/google-developer-experts/exploring-android-q-location-permissions-64d312b0e2e1)

![Screenshot 2019-11-08 at 12 51 08](https://user-images.githubusercontent.com/4030704/68474727-831dc300-0226-11ea-8500-7206e8d5cd42.png)


I hope this answers your question. I'm closing the issue for now. However, feel free to open it again if you think Dexter is not able to handle this permission properly.

**Comment by dds861** [comment]
on api 30 it doesn't work

**Comment by PavelMostovoy** [comment]
it works on API 29, but doesn't work on API 30
