### ISSUE TITLE
Not receiving permission dialog if i reject for first time

### ISSUE THREAD

**Issue by sagarchoudhary96** [Karumi/Dexter#241]
### Expected behaviour
It should ask for permission again.

### Actual behaviour
It don't ask for permission.

### Steps to reproduce
ask for permission on a button click , don't accept it and then again click the button to ask permission.

### Version of the library
"com.karumi:dexter:5.0.0"

**Comment by AcnNuriSezgin** [comment]
It happens to me.

**Comment by sagarchoudhary96** [comment]
@AcnNuriSezgin , it's working fine.
