### ISSUE TITLE
Show snackbar when permission is denied

### ISSUE THREAD

**Issue by jay-ph** [Karumi/Dexter#245]
### Expected behavior

Should show a message (snackbar or anything else) when one or multiple permissions are denied.

### Actual behavior

This feature is available for single permission only.

### Version of the library

latest one

**Comment by pedrovgs** [comment]
@jay-ph this is something you'll have to implement by yourself. Dexter only provides code needed to handle the approved or denied permissions. The code to show feedback to the user is up to you and your implementation details 😃
