### ISSUE TITLE
Location Permission

### ISSUE THREAD

**Issue by karanbeer123** [Karumi/Dexter#247]
### Expected behaviour
When i have grant the locaion permission after that service is start .and i have got the lat lng and when i have revoke the location permission manually from the setting class. and then got back to class then the got crash due to location service is running how can  i have handle this issue..

### Version of the library
4.2.0

**Comment by pedrovgs** [comment]
Plase @karanbeer123 update the library version to the latest one and create a sample project reproducing your issue. With the description you provided, I won't be able to fix or review anything. Thank you in advance.
