### ISSUE TITLE
Dexter probably should be able to launch transparent activity using any context

### ISSUE THREAD

**Issue by deinlandel** [Karumi/Dexter#255]
### Expected behaviour
Dexter probably should be able to launch transparent activity using any context

### Actual behaviour
Context which is received in BroadcastReceiver.onReceive(), for example is neither activity nor application context. Since startTransparentActivityIfNeeded adds FLAG_ACTIVITY_NEW_TASK only if context is an instance of Application, this leads to an exception:
`android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3831)`

### Steps to reproduce
Create a broadcast receiver and in onReceive try to obtain permissions using Dexter on Android 9+

### Version of the library
6.1.0

**Comment by pedrovgs** [comment]
Hello @deinlandel this is the first time I see you need to check any permission from a broadcast receiver but I guess this is an "expected" scenario since your latest PR #253. I'm fixing this issue which will be released as soon as the PR is merged. 

Thanks for reporting!
