### ISSUE TITLE
Attribute "borderWidth" has already been defined

### ISSUE THREAD

**Issue by GradyYu** [Karumi/Dexter#26]
android support library 23.1.1 has been defind "borderWidth"

**Comment by pedrovgs** [comment]
Hi @GradyYu your problem could be related with the compatibility library usage. Dexter uses a version and maybe you are using another one. Can you exclude the Android compatibility library from Dexter and try again? This could give use a clue to fix your problem.

Here you have an example:

```groovy
dependencies {

compile('org.hibernate:hibernate:3.1') {

//excluding a particular transitive dependency:

exclude module: 'cglib' //by artifact name

exclude group: 'org.jmock' //by group

exclude group: 'org.unwanted', module: 'iAmBuggy' //by both name and group

}

}
```

**Comment by GradyYu** [comment]
@pedrovgs Thanks!
