### ISSUE TITLE
Exception when requesting permissions after rationale shown

### ISSUE THREAD

**Issue by ANPez** [Karumi/Dexter#27]
I am creating a new permission request after showing the rationale to the user, and the library si failing with the exception:

   Only one Dexter request at a time is allowed

**Comment by Serchinastico** [comment]
Hi @ANPez 

How are you handling the rationale? When the library calls ``onPermissionRationaleShouldBeShown`` it will handle you a ``PermissionToken`` that you must use to continue/cancel the permission request. If you don't use your token then Dexter will get blocked waiting for a response from the token and won't let you ask for other permissions.

To sum up, review your listener and check if you are calling one of the token methods somewhere in your ``onPermissionRationaleShouldBeShown`` implementation.

**Comment by ANPez** [comment]
Could you please document that behaviour? I couldn't find any examples and I am sure I'm using it the wrong way :)

**Comment by Serchinastico** [comment]
It is already documented in the sample & jdoc but I've just added a paragraph in the README to make it more visible for everyone (https://github.com/Karumi/Dexter#showing-a-rationale)

Hope it helps!

**Comment by ANPez** [comment]
Thanks!
