### ISSUE TITLE
Permissions should be granted when the permission did not exist

### ISSUE THREAD

**Issue by diego-gomez-olvera** [Karumi/Dexter#3]
There is a blog post about permissions:

 https://commonsware.com/blog/2015/11/09/you-cannot-hold-nonexistent-permissions.html

That explains that the compatibility library does not handle well the permissions in Android versions before a certain permission was added. I was planning to create a little snippet to deal with this issue, but having this library it would be convenient if it would take care of it.

**Comment by pedrovgs** [comment]
Thanks for the issue @diego-gomez-olvera! We've been talking about this issue for the last two days and implement this could be quite interesting but hard to maintain at the same time. We need to review manually all the permissions declared per Android version and create a map with this information. Maybe you want to send us a PR ;)

**Comment by diego-gomez-olvera** [comment]
@pedrovgs I can send a PR whenever I have time. It is a bit tedious task, but it does not require maintenance once it is done. API 23+ do not need it, and I intended to support since API 15 (the currently minimum reasonable version), and for that you can simply check the API diff:

http://developer.android.com/sdk/api_diff/22/changes/android.Manifest.permission.html

or parse the source code of the Manifest.permission class web page:

view-source:https://developer.android.com/reference/android/Manifest.permission.html

Do you intend to support API versions lower than 15?

**Comment by pedrovgs** [comment]
I have to talk about the min sdk version used to @Serchinastico. We have a PR to support API 10 as min sdk version pending to review, but I don't know if we should support it. Thoughts @Serchinastico @flipper83 ?

**Comment by Serchinastico** [comment]
I can do some testing with old android versions to see if we will have to deal with something else but keep in mind that only ~4% of android users would potentially benefit from this feature so I don't see it as a major issue

**Comment by pedrovgs** [comment]
@Serchinastico can we close this issue?
