### ISSUE TITLE
does not deal with saveinstancestate

### ISSUE THREAD

**Issue by andaag** [Karumi/Dexter#30]
I see your using static references to instance, this means if your activity is killed during the request (can happen with rotate or if the user switches out of the app to google a permission) this will not work.

**Comment by davideme** [comment]
Yes we are using static reference, but as mention in the Readme https://github.com/Karumi/Dexter#screen-rotation, Dexter allow you to handle theses cases with continuePendingRequestsIfPossible.
Take a look to the documentation and tell us if we are missing something that can be helpfull to be more explicit.

**Comment by andaag** [comment]
I think  it was more a lack of research on my side than the lacking documentation that was at fault there. Sorry about the noise!

**Comment by pedrovgs** [comment]
No problem :)
