### ISSUE TITLE
Keep execution context on permission requested.

### ISSUE THREAD

**Issue by cmc00022** [Karumi/Dexter#31]
Hi guys,

I just found out a behaviour that I was not expecting, although I'm not quite sure it should be consider as an issue. But definitely it's something I wasn't expecting.

If a permission is requested from a background thread the result is returned on the main thread. 

I was having a look at the code and the reason seems to be that when the internal activity that the lib uses is started it changes the thread under the covers.

I'd like to know what are you thoughts about this.

Cheers.

**Comment by Serchinastico** [comment]
Hi @cmc00022 

Definitely we are not taking care of which thread we are calling the callback on, we need to discuss if that's something we want to give support though. I think it'd be rather easy but I want to talk about it with @pedrovgs and @flipper83 first

**Comment by cmc00022** [comment]
Thanks for considering :+1:

**Comment by pedrovgs** [comment]
@cmc00022 do you need to keep te execution context?

**Comment by cmc00022** [comment]
On my particular case I just need the callback to be returned out of the ui thread. 

As a more general solution, I'd say that ideally it should just return the callback on the thread that made the request.

**Comment by pedrovgs** [comment]
As you said, this is not needed right now, so we'll wait for a PR to implement this feature. Feel free to send one if you want :)

**Comment by cmc00022** [comment]
I'll create a PR as soon as I can.

Thanks.

**Comment by cmc00022** [comment]
@pedrovgs thinking about adding a sync public method for clients that expect the result to be returned on the same thread, any thoughts?

**Comment by pedrovgs** [comment]
Definitively you should add a new method to the api, but this can't be sync. You'll have to keep the looper used in the code invocation and then create a handler to notify the listener over that looper. The method can't be synchronous because we have to start an activity and in addition, if we the library is used from the UI thread we don't want to block it.

**Comment by cmc00022** [comment]
Ok, I'll try to find some spare time and have a working solution by the end of this week. I'll get back to you then.

Thanks.
