### ISSUE TITLE
DexterActivity is still leak even set launchMode="singleTask"

### ISSUE THREAD

**Issue by johnwatsondev** [Karumi/Dexter#34]
Snapshot:  
![e40bde2d0fb41a0fd4f5e3276a3813a4](https://cloud.githubusercontent.com/assets/12760754/11835402/31189fe6-a40e-11e5-8af1-fd966ec754a6.jpg)
Proguard mapping info:  
```
com.karumi.dexter.Dexter -> com.karumi.dexter.Dexter:  
    com.karumi.dexter.DexterInstance instance -> a  
com.karumi.dexter.DexterInstance -> im:  
    android.app.Activity activity -> i
```
PR #25 have tried to fix this issue. Please review and test it.
Thanks a lot!

**Comment by Serchinastico** [comment]
Hi @johnwatsondev 

Thanks for reporting, could you please tell us which version of Dexter are you using?

**Comment by johnwatsondev** [comment]
2.1.2 :smiley:

**Comment by Serchinastico** [comment]
I might have an idea what the problem might be, let me take a look and I'll let you know

**Comment by Serchinastico** [comment]
I'm preparing release 2.1.4 with the fix. Again, thanks for reporting!

**Comment by johnwatsondev** [comment]
@Serchinastico You're welcome. Thanks for feedback quickly!
