### ISSUE TITLE
Not checking permission request API under 23 (M)

### ISSUE THREAD

**Issue by TheFinestArtist** [Karumi/Dexter#43]
I released my app using dexter and I found that there is some bugs with Android system and I cause `Only one dexter request is allowed at a time` exception. 
I'm hoping not to check permission stuff under API version 23.

Here is my codes and error message.
```java
Dexter.checkPermissions(new MultiplePermissionsListener() {
                @Override
                public void onPermissionsChecked(MultiplePermissionsReport report) {
                    if (report.areAllPermissionsGranted())
                        showCropSheetView();
                    else
                        Snackbars.alert(CropActivity.this, getString(R.string.errorMessageExternalStoragePermission));
                }

                @Override
                public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {
                    Snackbars.alert(CropActivity.this, getString(R.string.errorMessageExternalStoragePermission));
                    token.continuePermissionRequest();
                }
            }, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE);
```

![untitled](https://cloud.githubusercontent.com/assets/3123741/12381114/ad5197a8-bdc6-11e5-815f-c0765545af35.png)

**Comment by Serchinastico** [comment]
Hi @TheFinestArtist,

Seems like your problem is caused because you are asking for permissions more than once. This may happen because you are explicitly doing so or because you have a permission that has not been resolved yet (it might be calling your `onPermissionRationaleShouldBeShown` and you are not using the token, I know this is not the case thanks to your snippet but just wanted to put it here so that others with the same problem can read it).
The easiest solution is to call `Dexter.isRequestOngoing()` before doing anything else:

```java
if (!Dexter.isRequestOngoing()) {
    Dexter.checkPermission(...);
}
```

Contact us if the problem persists.

**Comment by TheFinestArtist** [comment]
@Serchinastico Thanks for letting me know there is a method `Dexter.isRequestOngoing()` but in my case, even though I consumed the token `token.continuePermissionRequest();`, Dexter still think the request is on going. I think there must be some bug for device that are using API under 23.

Following is what I did to handle this case. Since we don't need to care about run time permission for device under API 23, I added `if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M)` to check device API version and if it is under 23, I simply didn't use Dexter.
```java
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            showCropSheetView();
        } else {
            Dexter.checkPermissions(new MultiplePermissionsListener() {
                @Override
                public void onPermissionsChecked(MultiplePermissionsReport report) {
                    if (report.areAllPermissionsGranted())
                        showCropSheetView();
                    else
                        Snackbars.alert(CropActivity.this, getString(R.string.errorMessageExternalStoragePermission));
                }

                @Override
                public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {
                    Snackbars.alert(CropActivity.this, getString(R.string.errorMessageExternalStoragePermission));
                    token.continuePermissionRequest();
                }
            }, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE);
        }
```

**Comment by Serchinastico** [comment]
Hi,

It seems like an issue with pre-M devices, we'll take a look and report you back whenever we find out what the problem is.

**Comment by TheFinestArtist** [comment]
@Serchinastico This is just my guess. I think the methods supported by Android system such as `checkSelfPermission` or whatever doesn't work as it should be with rooted phones. It is just my guess.

**Comment by TheFinestArtist** [comment]
@Serchinastico I think you are right! `!Dexter.isRequestOngoing()` works fine!
