### ISSUE TITLE
Handle SYSTEM_ALERT_WINDOW permission

### ISSUE THREAD

**Issue by dhavaljivani** [Karumi/Dexter#46]
How to handle SYSTEM_ALERT_WINDOW permission using Dexter.

**Comment by Serchinastico** [comment]
Hi @dhavaljivani 

`SYSTEM_ALERT_WINDOW` and `WRITE_SETTINGS` are permissions that are not requested in the usual way with `requestPermissions` but with a special intent. Dexter doesn't support those permissions yet but we are open to PRs :)
