### ISSUE TITLE
Black screen with Launch Activity without Toolbar.

### ISSUE THREAD

**Issue by marcellogalhardo** [Karumi/Dexter#48]
Hi, I'm using Dexter-Lib on a project and I am having a problem that always displays a black screen. The details to simulate are simple:

1 - build.app configurations.

    android {
        compileSdkVersion 23
        buildToolsVersion '23.0.2'

        defaultConfig {
            minSdkVersion 15
            targetSdkVersion 23
            versionCode 1
            versionName "1.0"
            multiDexEnabled true
        }
    }

2 - My style.

    <style name="LaunchTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorAccent">@color/material_white_1000</item>
        <item name="colorControlNormal">@color/material_white_1000</item>
        <item name="colorControlActivated">@color/material_white_1000</item>
        <item name="colorControlHighlight">@color/material_white_1000</item>
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
    </style>

3 - I create a simple builder to call the Dexter Library.

    PermissionValidator.with(activity)
            .setTitle(R.string.permission_read_contacts_title)
            .setMessage(R.string.permission_read_contacts_message)
            .setDeniedMessage(R.string.permission_read_contacts_denied_message)
            .setPermission(Manifest.permission.READ_CONTACTS)
            .setOnPermissionGrantedListener(new OnPermissionGrantedListener() {
                @Override
                public void onPermissionGranted() {
                    activity.startActivityForResult(getContactsIntent(), PICK_CONTACT_REQUEST_CODE);
                }
            })
            // .setOnPermissionRationaleShouldBeShownListener(new DefaultOnPermissionRationaleShouldBeShownListener())
            .validate();

4 - The code called by Validate (if necessary).

    if (!Dexter.isRequestOngoing()) {
        Dexter.checkPermission(new PermissionListener() {
            @Override
            public void onPermissionGranted(PermissionGrantedResponse response) {
                if (onPermissionGrantedListener != null) {
                    onPermissionGrantedListener.onPermissionGranted();
                }
            }

            @Override
            public void onPermissionDenied(PermissionDeniedResponse response) {
                if (onPermissionDeniedListener != null) {
                    onPermissionDeniedListener.onPermissionDenied();
                }
            }

            @Override
            public void onPermissionRationaleShouldBeShown(PermissionRequest permission, final PermissionToken token) {
                if (onPermissionRationaleShouldBeShownListener != null) {
                    onPermissionRationaleShouldBeShownListener.onPermissionRationaleShouldBeShown(context, token, title, message, deniedMessage);
                }
            }
        }, permission);
    }

This code works perfectly when you define a Toolbar. But when I do this in my LoginActivity (which does not use a Toolbar), I get one of two messages when I call the .validate () method and a beautiful black screen:

    1 - You need to use a Theme.AppCompat theme (or descendant) with this activity`.
    2 - android.view.WindowLeaked: Activity br.com.mobicare.recarga.ui.activity.LaunchActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{707ca14 V.E...... R....... 0,0-1080,737} that was originally added here`

![Result](http://i.imgur.com/YT669bH.png)

Could anyone help me?

**Comment by marcellogalhardo** [comment]
I discovered that the problem occurs in one Activity that has set in its manifest tag: `android: noHistory = "true"`. This is a bug or was it my fault?

**Comment by Serchinastico** [comment]
Hi @marcellogalhardo,

I'd have to do some testing but I'd say that the themes system is somehow conflicting, keep in mind that the inner `DexterActivity` instance is using a non-appcompat theme (our bad and something we should probably take a look at).

I'll try to reproduce and debug the issue this week and let you know our findings.

Thanks for reporting!

**Comment by Serchinastico** [comment]
I've been trying with several configurations but I can't reproduce your problem.
It would be much easier for us if you can provide us with a minimum project where the bug happens. 

Either that or you can wait until we release a new version of Dexter which presumably will contain a fix to how we handle the inner activity but I'm not sure if it'll solve your problem.

**Comment by marcellogalhardo** [comment]
Thank you for the feedback. I will create a project with the problem to provide for you this week!

**Comment by marcellogalhardo** [comment]
@Serchinastico the code is available in the repository: [Bug Dexter Black Screen](https://github.com/marcellogalhardo/bug_dexter_black_screen/blob/master/README.md)

Note the following details:
- Styles: AppTheme.
- AndroidManifest: Activity 'android: noHistory = "true"'

When you start the application, it should display a white screen says "Hello World."
When the permission dialog appears, select the "Deny" option.

Note that the application will behave in the following ways:
- Will keep a black screen (usually on the first run).
- Will close the application (the next time).

I hope this helps.

**Comment by Serchinastico** [comment]
Hi @marcellogalhardo 

I now understand what's happening, as you pointed out, the important thing is the `noHistory = "true"` config. When Dexter is called, it creates a new activity internally to request the permissions and pushes it into the stack, this causes your `LoginActivity` to be completely removed as it's not the top activity anymore (http://developer.android.com/guide/topics/manifest/activity-element.html#nohist).
Whatever it draws under the `DexterActivity` is left to our imagination (usually a black background or the launcher if the removed activity was the only one).

Sadly, I don't see how we can handle that scenario, the only viable solution would be to use your own activity to request permissions and that's something that you can probably do better on your own instead of using Dexter.

**Comment by Serchinastico** [comment]
I added a disclaimer in the README warning users of the library to don't use the `noHistory` flag.
