### ISSUE TITLE
Requesting some permissions doesn't work

### ISSUE THREAD

**Issue by JcMinarro** [Karumi/Dexter#5]
When you request for a `Manifest.permission.ACCESS_COARSE_LOCATION` or `Manifest.permission.ACCESS_FINE_LOCATION` Dexter doesn't work. It is because the hashcode of these permissions is a negative value and you can't use a nevative value as a `requestCode`.

**Comment by Serchinastico** [comment]
Nice finding, there is already a PR ongoing to fix this issue.
Thanks for reporting!

**Comment by JcMinarro** [comment]
I am going to do a PR that fixes it and add other funcionality ;)

**Comment by Serchinastico** [comment]
Thanks @JcMinarro! Do you mind creating one PR for the fix and another one for the new functionality? It will make it easier for us to validate them.

**Comment by JcMinarro** [comment]
Ups, I have created the two PRs together. Sorry.
The fix is only one line.
if you consider necessary to split it, let me now

**Comment by Serchinastico** [comment]
Your fix has been included in v1.0.2, thanks!

**Comment by pedrovgs** [comment]
Thanks @JcMinarro!
