### ISSUE TITLE
Make the Dexter API fluent

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Dexter#54]
I opened an issue talking about adding a new parameter to notify Dexter errors (#53) and seems to me that adding new parameters to the current API will eventually make it impossible to develop.

I think it would be much better to create a fluent API to use Dexter both in readability and extensibility. The proposed API would be used like:

``` java
public void someMethod() {
    Dexter.withPermissions(Manifest.permission.CAMERA, Manifest.permission.READ_CONTACTS)
          .withListener(someListener)
          .withErrorListener(errorListener)
          .onSameThread()
          .check();
}
```

Thoughts are more than welcome.

**Comment by Sloy** [comment]
Awesome idea!
I would personally prefer a more semantic or granular API, such as 
```
public void someMethod() {
    Dexter.forPermissions(Manifest.permission.CAMERA, Manifest.permission.READ_CONTACTS)
          .doOnGranted(someListener)
          .doOnDenied(errorListener)
          .doWhenRationaleShouldBeShown(someListener)
          .onSameThread()
          .check();
}
```

It's just my personals and maleable opinion. But the idea of a fluent API is great.

**Comment by Serchinastico** [comment]
I can see why you'd separate the `doWhenRationaleShouldBeShown` callback but I can't think of any use case where you wouldn't handle at least the two basic responses, `doOnGranted` and `doOnDenied`. Anyways, you can always create a composite listener with a generic `onDenied` listener and specific `onGranted` implementations, actually, you can do the same with the rationale callback as well.

In this case, I'd rather keep a single interface than splitting it into three for three reasons: it's easier to implement, it's easier to understand (IMHO) and we can move towards simpler interfaces whenever we want keeping it backwards compatible (but not the other way around!).

**Comment by Sloy** [comment]
Yep you're right, it doesn't make much sense implementing only one of the two callbacks. I was thinking more on lambda support. Two methods with one functional interface can use lambdas, but one method with a two method interface can't.
But of course, at the current state of Android, lambda support should not be a priority for an API design :p

Maybe a middle solution would be a RxJava-like listener supporting both forms, one interface with two methods and two interfaces with one method.

Anyway, just that you have thought about it is good enough for me. The real advantage here is the fluent API \o/

**Comment by pedrovgs** [comment]
@Serchinastico do you have a branch to implement this one? Could be great to publish the 3.0.0 version with my last PR #73 and this one.
