### ISSUE TITLE
Show the permission dialog after a defined delay

### ISSUE THREAD

**Issue by rocboronat** [Karumi/Dexter#56]
### Expected behaviour
Add a way to show the Dialog after a defined delay

### Actual behaviour
The permission delay appears just when we call it. If we want to show it after some time, we've to write it in our apps

### Steps to reproduce
Call *Dexter.checkPermission()*

### Version of the library
2.2.2

If you want, I can do it and launch a PR. Are you interested on it? If you are not interested in this feature, don't hesitate to simply close this issue :·)

Thanks for your work!

**Comment by pedrovgs** [comment]
I think this should not be inside Dexter. If you want to add a delay you can add it to your project doing something like:
```java
handler.postDelayed(new Runnable() {
 public void run() {
    Dexter.checkPermission()
 }
}, delayTime());

```

This code could not compile xD but I guess you get the idea.

If @Serchinastico or @flipper83 think the same, I guess we are going to close this issue.

**Comment by Serchinastico** [comment]
Hi @rocboronat 

I personally don't think this feature should be implemented in Dexter, to me it's a presentation detail that you should implement in your applications and it's completely unrelated to permissions. I'd like to hear @pedrovgs or @flipper83 opinion anyways.

Thanks for the proposal!

**Comment by rocboronat** [comment]
Totally understood. Thanks for the quick answer!
