### ISSUE TITLE
Permission Dialog not showing at first launch

### ISSUE THREAD

**Issue by geekyRJ** [Karumi/Dexter#60]
### Expected behavior

 Application should ask camera permission at first time  camera call from my app.

### Actual behaviour

After installing application in device when i click camera button it is not showing camera permission dialog instead it is directly opening camera. but after clearing app data  in application setting. it started showing permission request dialog. Now started work fine.  even i am targating api 23 and my device also using marshmallow. if change the package name of app then it work normal as i want

### Version of the library
I am using latest version

**Comment by pedrovgs** [comment]
Hi @geekyRJ! to be able to help you we need to see how you are using Dexter to handle the user permissions. Can you paste here the code related to the permissions you have in your app?

**Comment by geekyRJ** [comment]
Hi @pedrovgs  here is my code
## in Manifest file  

` <application
        android:name="com.mypackagename.SampleApplication"
        android:icon="@drawable/ic_logo_karumi"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >

  <activity
            android:name="com.karumi.dexter.DexterActivity"
            android:launchMode="singleTask"
            android:theme="@style/Theme.Transparent" />
 </application> `

## in My Activity Class

public class WelcomeActivity extends AppCompatActivity implements OnClickListener
{
	public static final String TEMP_PHOTO_FILE_NAME = "img_temp.jpg";
	static File mFileTemp;
	private Intent intent;
	private Uri imageFileUri = null;

	private MultiplePermissionsListener allPermissionsListener;
	private PermissionListener readExternalStoragePermissionListener;
	ViewGroup rootView;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_welcome);
		rootView = (ViewGroup) findViewById(android.R.id.content);
		createPermissionListeners();
		Dexter.continuePendingRequestsIfPossible(allPermissionsListener);

		createAppDir();

		findViewById(R.id.btn_camera).setOnClickListener(this);
		findViewById(R.id.btn_gallery).setOnClickListener(this);
	}

	private void createAppDir() {
		String root = Environment.getExternalStorageDirectory().toString();
		new File(root + "/" + getString(R.string.app_name) + "/temp").mkdirs();
		String state = Environment.getExternalStorageState();
		if (Environment.MEDIA_MOUNTED.equals(state)) {
			mFileTemp = new File(root + "/" + getString(R.string.app_name)
					+ "/temp/", TEMP_PHOTO_FILE_NAME);
		} else {
			mFileTemp = new File(getFilesDir(), TEMP_PHOTO_FILE_NAME);
		}
	}

	@Override
	public void onClick(View v) {
		switch (v.getId()) {
		case R.id.btn_camera:
			onAllPermissionsButtonClicked();
			
			break;
		case R.id.btn_gallery:
			intent = new Intent(Intent.ACTION_PICK);
			intent.setType("image/*");
			startActivityForResult(intent, Constants.REQUEST_CODE_GALLERY);
			break;
		}
	}
	private void CallCamera() 
	{
		Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
		try {
			imageFileUri = null;
			String state = Environment.getExternalStorageState();
			if (Environment.MEDIA_MOUNTED.equals(state)) {
				imageFileUri = Uri.fromFile(mFileTemp);
			} else {
				imageFileUri = InternalStorageContentProvider.CONTENT_URI;
			}
			intent.putExtra(android.provider.MediaStore.EXTRA_OUTPUT,
					imageFileUri);
			intent.putExtra("return-data", true);
			startActivityForResult(intent, Constants.REQUEST_CODE_TAKE_PICTURE);
		} catch (ActivityNotFoundException e) {

		}
	}

	@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) 
	{
		if (resultCode != RESULT_OK) 
		{
			return;
		}

		switch (requestCode) 
		{
		case Constants.REQUEST_CODE_GALLERY:
			try 
			{
				InputStream inputStream = getContentResolver().openInputStream(data.getData());
				FileOutputStream fileOutputStream = new FileOutputStream(mFileTemp);
				copyStream(inputStream, fileOutputStream);
				fileOutputStream.close();
				inputStream.close();

				Intent intent = new Intent(this, PhotoCutActivity.class);
				intent.putExtra("mImageUri", mFileTemp.getPath());
				startActivity(intent);
			} catch (Exception e) {
			}
			break;

		case Constants.REQUEST_CODE_TAKE_PICTURE:
			Intent intent = new Intent(this, PhotoCutActivity.class);
			intent.putExtra("mImageUri", mFileTemp.getPath());
			startActivity(intent);

			break;
		}
		super.onActivityResult(requestCode, resultCode, data);
	}

	public static void copyStream(InputStream input, OutputStream output)throws IOException {
		byte[] buffer = new byte[1024];
		int bytesRead;
		while ((bytesRead = input.read(buffer)) != -1) 
		{
			output.write(buffer, 0, bytesRead);
		}
	}

	@Override
	protected void onResume() 
	{
		super.onResume();
		
	}
	public void onReadExternalStorageButtonClicked()
	{
		if (Dexter.isRequestOngoing()) 
		{
			return;
		}
		Dexter.checkPermission(readExternalStoragePermissionListener,Manifest.permission.READ_EXTERNAL_STORAGE);
	}

	public void onAllPermissionsButtonClicked()
	{
		if (Dexter.isRequestOngoing())
		{
			return;
		}
		Dexter.checkPermissions(allPermissionsListener,
				Manifest.permission.CAMERA,
				Manifest.permission.READ_EXTERNAL_STORAGE);
	}
	private void createPermissionListeners() 
	{
		PermissionListener feedbackViewPermissionListener = new SamplePermissionListener(this);
		MultiplePermissionsListener feedbackViewMultiplePermissionListener = new SampleMultiplePermissionListener(this);
		
		allPermissionsListener = new CompositeMultiplePermissionsListener(feedbackViewMultiplePermissionListener,SnackbarOnAnyDeniedMultiplePermissionsListener.Builder
						.with(rootView,R.string.all_permissions_denied_feedback)
						.withOpenSettingsButton(R.string.permission_rationale_settings_button_text).build());
		
		PermissionListener dialogOnDeniedPermissionListener = DialogOnDeniedPermissionListener.Builder
				.withContext(this)
				.withTitle(R.string.permission_rationale_header)
				.withMessage(R.string.readexternal_permission_denied_feedback)
				.withButtonText(R.string.permission_rationale_settings_button_text)
				.build();
		
		readExternalStoragePermissionListener = new CompositePermissionListener(feedbackViewPermissionListener,
				SnackbarOnDeniedPermissionListener.Builder
						.with(rootView,	R.string.readexternal_permission_denied_feedback)
						.withOpenSettingsButton(R.string.permission_rationale_settings_button_text)
						.build());
		
	}
	
	@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR1)
	public void showPermissionRationale(final PermissionToken token)
	{
		new AlertDialog.Builder(this)
				.setTitle(R.string.permission_rationale_title)
				.setMessage(R.string.permission_rationale_message)
				.setNegativeButton(android.R.string.cancel,
						new DialogInterface.OnClickListener() {
							@Override
							public void onClick(DialogInterface dialog,
									int which) {
								dialog.dismiss();
								token.cancelPermissionRequest();
							}
						})
				.setPositiveButton(android.R.string.ok,
						new DialogInterface.OnClickListener() {
							@Override
							public void onClick(DialogInterface dialog,
									int which) {
								dialog.dismiss();
								token.continuePermissionRequest();
							}
						})
				.setOnDismissListener(new DialogInterface.OnDismissListener() {
					@Override
					public void onDismiss(DialogInterface dialog) {
						token.cancelPermissionRequest();
					}
				}).show();
	}

	public void showPermissionGranted(String permission) 
	{
			CallCamera();
	}

	public void showPermissionDenied(String permission,	boolean isPermanentlyDenied) 
	{
		
	}
}

**Comment by Serchinastico** [comment]
Hi @geekyRJ 

I don't see anything wrong in your code. I'm wondering if you were doing a fresh install or the app was already installed on your device. If that was the case, it's possible that the installation process didn't clear the app's data and therefore your permissions state were stored from a previous execution.

**Comment by geekyRJ** [comment]
Thank you sir, I finally found the issue. the issue is only with my device. in other device it is working properly.

**Comment by jjimenez0611** [comment]
Hi have the same issue, my device is a S7 edge with nougat version 7.0...

The first launch of my app dexter don't work I hace to close the app and open again...

I call the Dexter library on the onCreate method...

**Comment by jjimenez0611** [comment]
I think is because I try to request the permissions but, in another process I made a intent to another activity.. And the Dexter dialog stay active and not show again...
