### ISSUE TITLE
Permission rational not showing on the first permission request

### ISSUE THREAD

**Issue by pkleczko** [Karumi/Dexter#61]
### Expected behaviour
onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) fires always when Dexter.checkPermissions is called

### Actual behaviour
Cannot understand why this happens but when I firstly call Dexter.checkPermissions with two permissions: Manifest.permission.ACCESS_FINE_LOCATION and Manifest.permission.ACCESS_COARSE_LOCATION onPermissionRationaleShouldBeShown is not called but instead dialog with permission request shows. What is more there is no "Never ask again" checkbox:
![screen1](https://cloud.githubusercontent.com/assets/910035/14982650/27cbde98-1138-11e6-8716-4e7377bdc544.png)

When I deny and call method second time, onPermissionRationaleShouldBeShown is called and I show my alertDialog and then permission request dialog has "Never ask again" checkbox.
![screen2](https://cloud.githubusercontent.com/assets/910035/14982727/adf7daa8-1138-11e6-9208-08f3a83ab695.png)

### Steps to reproduce
Dexter.checkPermissions(new CustomPermissionListener(), Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION);

Nexus 5, 6.0.1

### Version of the library
com.karumi:dexter:2.2.2

**Comment by Serchinastico** [comment]
Hi @pkleczko 

First of all, thanks for reporting. 

The behaviour you are describing is how actually Android permissions work, the first time you request any permission the system will simply show the dialog asking the user for her consent. If the user requests the same permission for the second time, the system will call the `shouldShowRequestPermissionRationale` callback to let you explain to your user why your app needs the requested feature. 

I recommend you to read the official runtime permissions documentation, specially the section referring to the rationale: [link](https://developer.android.com/training/permissions/requesting.html#perm-request)

**Comment by pkleczko** [comment]
Yes, you're rigth. I was not aware it works like this. Thanks for reply.

**Comment by Hoss3inf** [comment]
Dear @Serchinastico 
I was wondering if there is any way to let the user see the dialog the first time the app attempts to ask for the permission, as an explanation to the user why the app is asking for the permission?
thanks in advance.

**Comment by pedrovgs** [comment]
@Hoss3inf you can always show any or contextual help dialog before using Dexter.

**Comment by Hoss3inf** [comment]
@pedrovgs I just thought I can do it within Dexter. thanks for your reply.

**Comment by pedrovgs** [comment]
That's simple to implement and depends a lot on the user needs that we decided not to add that feature to the lib.
