### ISSUE TITLE
Dexter in a multi process environment

### ISSUE THREAD

**Issue by MaxToyberman** [Karumi/Dexter#63]
Is Dexter safe to use in a multi process environment ?

**Comment by pedrovgs** [comment]
Hi @MaxToyberman!

Dexter is ready to be used in a multi thread environment. You can invoke Dexter from different threads and choose the thread used to get the response if needed. Remember to check if there are requests going on before to check for a new permission.

Is this the answer to your question?

**Comment by pedrovgs** [comment]
@Serchinastico do you have anything else to add?

**Comment by Serchinastico** [comment]
Yup, if you need something more complex I'd recommend building it on top of the library

**Comment by MaxToyberman** [comment]
Hi @pedrovgs @Serchinastico  
I have added Firebase crash reporting to my project.
this is from the docs:

> Crash Reporting creates a separate background process to upload crash info. If your app extends the Android Application class, you must ensure it is multi-process safe. Otherwise, it may cause concurrency issues. When an app extends an Application object, this object gets instantiated for each process in a multi-process app

that means that Dexter.initialize will be called multiple times ? 
is it a problem? 

Thank you

**Comment by Serchinastico** [comment]
Hi @MaxToyberman 

`Dexter.initialize` method takes care of initializing its inner instance only once **but** it's not thread safe. If you call it from different threads it might have unexpected behaviour. I can't think of any situation where it shouldn't work but it wasn't designed with multithreading in mind I'd assume it won't work. 

If Firebase creates a different process, though, you'd be creating two different Dexter instances so there shouldn't be any issue AFAIK.

**Comment by pedrovgs** [comment]
I think we can close this issue :) Thanks for your questions!!!

**Comment by Parthgupta96** [comment]
Hi all 
I faced a similar issue when requesting permission from dexter in multiple processes, system permission dialog was not shown 
to fix this I have added below code in app manifest 

```
<activity
	android:name="com.karumi.dexter.DexterActivity"
	android:multiprocess="true"
	tools:node="merge" />
```
