### ISSUE TITLE
Improve documentation about showing the rationale

### ISSUE THREAD

**Issue by Serchinastico** [Karumi/Dexter#64]
When the user cancels a permission Dexter lets you show a rationale to your user, if the token is not used ever, the permission request might get stuck

**Comment by kvenn** [comment]
It is in the README [here](https://github.com/Karumi/Dexter#showing-a-rationale) but I'll admit, I missed it the first time as well...

**Comment by Serchinastico** [comment]
I guess we can just call `token.continuePermissionRequest();` by default in the empty implementations but that'd mean releasing a new major version (my fault, I missed this for 3.0.0). 

In the meantime, we can create a couple `BaseListener` implementations with that call and deprecate `EmptyListener`s.

**Comment by Serchinastico** [comment]
This is now available in v4.0.0
