### ISSUE TITLE
Allow access to Snackbar instance within SnackbarOnDeniedPermissionListener

### ISSUE THREAD

**Issue by rfgamaral** [Karumi/Dexter#66]
I have this use case where I'm using `SnackbarOnDeniedPermissionListener` to show a Snackbar notify the user of some denied permission with the Settings button allowing them to enable the required permission.

But I feel the need to perform some action when the Snackbar is dismissed (manually by opening the settings button or automatically when it times out). But I don't have access to the Snackbar instance so I can't invoke `setCallback` to handle the `onDismissed` callback. As such, I can't use `SnackbarOnDeniedPermissionListener` and had to roll out my own implementation of the same thing.

Maybe implement a `withCallback` method on the `SnackbarOnDeniedPermissionListener`?

What do you guys think? I could open a pull request for this...

**Comment by Serchinastico** [comment]
Hi @rfgamaral,

Those listeners are meant to be used for very simple things and as an example to implement your own. However, given they are included in the library, I don't see why we can't add such feature. It's not our number one priority but PRs are more than welcome.

Thanks for your feedback!

**Comment by pedrovgs** [comment]
Fixed in #69
