### ISSUE TITLE
Question about continue permission request for rationale

### ISSUE THREAD

**Issue by rfgamaral** [Karumi/Dexter#67]
If one handles `onPermissionRationaleShouldBeShown` to show a rationale to the user explaining why we need that particular permission - for instance, with an `AlertDialog` - and call `token.continuePermissionRequest()` to show the request permission dialog again, this leads into two dialogs.

Is there anyway to avoid this? I mean, show a rationale within the request permission dialog?

**Comment by Serchinastico** [comment]
Hi @rfgamaral (again :P)

I'm guessing you are talking about the `DialogOnDeniedPermissionListener` implementation. As in the other issue, I'd say that it sounds completely logical to me to have access to the alert being displayed or to close it automatically when the user chooses an option.

**Comment by rfgamaral** [comment]
Not necessarily.

Say I implement `PermissionsListener` and create my own `AlertDialog` inside `onPermissionRationaleShouldBeShown` to explain why I need a specific permission with my own words. Use selects `OK` and then I invoke `token.continuePermissionRequest()` and then the native rationale will be shown. Two dialogs.

I was looking for a way to get this into just one...

**Comment by Serchinastico** [comment]
What about closing the alert before calling the token?

**Comment by rfgamaral** [comment]
Not sure what you mean...

**Comment by Serchinastico** [comment]
I'm probably not following you here. 

I understand you want to show an alert dialog when you are asked to show the rationale to your user, then when the user accepts it, close the dialog and show the native view. Your listener implementation should be similar to the following:

```
@Override public void onPermissionRationaleShouldBeShown(PermissionRequest permission,
          final PermissionToken token) {
        new AlertDialog.Builder(SampleActivity.this)
            .setTitle("Hi there")
            .setMessage("Something something")
            .setPositiveButton("OK", new DialogInterface.OnClickListener() {
              @Override public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
                token.continuePermissionRequest();
              }
            })
            .show();
      }
```

Am I missing something?

**Comment by Serchinastico** [comment]
I'm probably not following you here. 

I understand you want to show an alert dialog when you are asked to show the rationale to your user, then when the user accepts it, close the dialog and show the native view. Your listener implementation should be similar to the following:

```
@Override public void onPermissionRationaleShouldBeShown(PermissionRequest permission,
          final PermissionToken token) {
        new AlertDialog.Builder(SampleActivity.this)
            .setTitle("Hi there")
            .setMessage("Something something")
            .setPositiveButton("OK", new DialogInterface.OnClickListener() {
              @Override public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
                token.continuePermissionRequest();
              }
            })
            .show();
      }
```

Am I missing something?

**Comment by rfgamaral** [comment]
That will give you two dialogs, your own and the rationale one. What I wanted was to have a single dialog with my own rationale words, not the platform's. But I guess this is just how the Android framework works and there's nothing this library can do about it. Feel free to close this issue.

**Comment by Serchinastico** [comment]
Ok, I think I got what you meant.

As you said, the framework doesn't let you customize in any way the native dialog so there is no way you can do that.
