### ISSUE TITLE
Keyboard does not open when checking permissions < android M

### ISSUE THREAD

**Issue by pixis** [Karumi/Dexter#80]
Probably because of the transparent activity.

A possible fix is:
```
getWindow().addFlags(
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                        | WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                        | WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE);
```

### Version of the library

2.3.0

**Comment by Serchinastico** [comment]
Hi @pixis,

Are you trying to open the keyboard while displaying the permissions request dialog? If that's the case, we can't do much as it's handled by the framework. If it's a problem while showing the rationale... I don't think it's safe to modify the window from the library. 

Can you describe us what's your use case? I don't fully understand why would you want to show the keyboard while requesting permissions to your user.

**Comment by Serchinastico** [comment]
I'll close the issue until further information is provided.

**Comment by nikitoSha** [comment]
I have the same issue. Step-by-step:
1. open activity;
2. at OnCreate:
Dexter.withActivity(this)
                .withPermissions(Manifest.permission.READ_EXTERNAL_STORAGE,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE)

3. Touch edit -> no keyboard.
4. press "back";
5. touch edittext -> keyboard showing.

**Comment by djx-y-z** [comment]
**Faced with the same and found a solution, I hope someone will help:** you must call "token.continue Permission Request();" in the "onPermissionRationaleShouldBeShown" event of your "PermissionListener".

`Dexter.withContext(activity)
            .withPermissions(
                    Manifest.permission.ACCESS_FINE_LOCATION,
                    Manifest.permission.ACCESS_COARSE_LOCATION
            )
            .withListener(new MultiplePermissionsListener() {
                @SuppressLint("MissingPermission")
                @Override
                public void onPermissionsChecked(MultiplePermissionsReport report) {
                }

                @Override
                public void onPermissionRationaleShouldBeShown(List<PermissionRequest> permissions, PermissionToken token) {
                    token.continuePermissionRequest();
                }
            })
            .check();`

**Comment by traviszim** [comment]
Thank you in obviously new to this, lessening my damage as I go along

**Comment by vamoruso** [comment]
> **Faced with the same and found a solution, I hope someone will help:** you must call "token.continue Permission Request();" in the "onPermissionRationaleShouldBeShown" event of your "PermissionListener".

token.continuePermissionRequest();  saved my day. Thx
