### ISSUE TITLE
Can not find withCallback

### ISSUE THREAD

**Issue by chenwulue** [Karumi/Dexter#82]
I can't find `SnackbarOnDeniedPermissionListener.Builder.withCallback` API

### Version of the library
`com.karumi:dexter:2.2.2`

**Comment by rfgamaral** [comment]
You have to update to `v2.3.0` where `withCallback` was added. It's not available on previous versions.

**Comment by Serchinastico** [comment]
That's right!

Closing the issue for now, if you still have problems with the callback let us know or reopen this ticket.
