### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by w0080626** [Karumi/Dexter#83]
Android 6.0 version of the device can run normally, but run on earlier versions of the equipment, procedure will collapse.

``` java
if (Build.VERSION.SDK_INT >= 23) {  
    // Marshmallow+  
} else {  
    // Pre-Marshmallow  
}  
```

But this will cause the program to become bloated.A better solution is to use the Support Library v4 repository method to replace the original method, it will save for different versions of the device respectively provide code:
``` java
// Modify Activity.checkSelfPermission()
ContextCompat.checkSelfPermission()  
```
The code is more concise

**Comment by Serchinastico** [comment]
Hi @w0080626 

There is no need to make Android version checks from Dexter, we are already using `ContextCompat.checkSelfPermission()`!

Which version of the library are you using?
