### ISSUE TITLE
Gradle Failed to resolve Dexter

### ISSUE THREAD

**Issue by hiteshsahu** [Karumi/Dexter#85]
### Expected behaviour
Gradle should be able to compile Dexter Lib into existing project

### Actual behaviour
Gradle cant resolve Dexter see screen shot

![dexter_undefined](https://cloud.githubusercontent.com/assets/4076925/18174444/3471ee78-708b-11e6-8609-6657b1cb6edd.png)

### Steps to reproduce

Add `compile 'com.karumi:dexter:2.2.2'` into gradle build file

### Version of the library
2.2.2

**Comment by Serchinastico** [comment]
Hello @hiteshsahu,

I think the problem is probably in your build file as I've been able to load that version of the library without problems. Did you add Maven Central to your dependency repositories? Make sure you have something similar to this in your `build.gradle`:

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
}
```

If the problem persists, send us your `build.gradle` to see if we can detect what's going on.

Thanks for reporting!

**Comment by hiteshsahu** [comment]
Maven is subset of JCenter so it should work for `JCenter` as well , Tested it today with `jCenter` again and It **worked without any problem**. This is really weird  and I cant think of why this was happening . For now I am closing this issue .

I am adding current Build Gradle for future reference 

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.hiteshsahu.soundcloudwaveformgeneratorandroid"
        minSdkVersion 17
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:design:24.2.0'
    compile 'com.karumi:dexter:2.2.2'


}
```

 app gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
