### ISSUE TITLE
Only one permission request at a time.

### ISSUE THREAD

**Issue by liqian685** [Karumi/Dexter#9]
How can I deal this：

java.lang.IllegalStateException: Only one permission request at a time. Currently handling permission: [android.permission.WRITE_EXTERNAL_STORAGE]
11-20 00:15:17.036 27963-27963/? E/CustomActivityOnCrash:     at com.karumi.dexter.DexterInstance.checkPermission(DexterInstance.java:51)
11-20 00:15:17.036 27963-27963/? E/CustomActivityOnCrash:     at com.karumi.dexter.Dexter.checkPermission(Dexter.java:52)

**Comment by Serchinastico** [comment]
Hi @liqian685.

This is a limitation we forced to avoid weird interactions with Dexter. Right now users can only request one permission at a time, this means you have to completely *resolve* one permission(i.e. wait to receive a ``onPermissionGranted`` or ``onPermissionDenied`` call) before requesting another. We are implementing the possibility to ask for multiple permissions with a single Dexter call but it hasn't been released yet.

If this is not your problem, it might be that you are not using the ``PermissionToken`` in your ``PermissionListener::onPermissionRationaleShouldBeShown`` implementation. Remember that you must use the token to continue/cancel the request process or Dexter will get stuck and won't let you ask for new permissions.

I hope it helps!

**Comment by liqian685** [comment]
It work when i use the token. thanks

**Comment by Serchinastico** [comment]
You are welcome, if the problem reoccur we might need to rethink that part
