### ISSUE TITLE
REQUEST_IGNORE_BATTERY_OPTIMIZATIONS

### ISSUE THREAD

**Issue by KamyarGhajar** [Karumi/Dexter#91]
Hi
How Can I get the `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission to opt-out my app from android doze in android M?

**Comment by Serchinastico** [comment]
Hi @KamyarGhajar

That permission is not handled in the same way runtime permissions are. If you want to ask for that permission, you will need to add the `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission to your manifest and send an intent with the `ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` action. You can read more about it in https://developer.android.com/reference/android/provider/Settings.html#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS.

At some point, we might want to include some strategies to handle this kind of permissions in the same fashion but right now it's not something we want to add.

Thanks for reporting!

**Comment by KamyarGhajar** [comment]
Thank you @Serchinastico

**Comment by amadeu01** [comment]
@Serchinastico 
> An app holding the REQUEST_IGNORE_BATTERY_OPTIMIZATIONS permission can trigger a system dialog to let the user add the app to the whitelist directly, without going to settings. The app fires a ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS Intent to trigger the dialog.

The [documentation](https://developer.android.com/training/monitoring-device-state/doze-standby.html) says that is possible to request the permission and do not have to lead the user to the settings screen.

**Comment by mwarning** [comment]
@Serchinastico `<uses-permission-sdk-23 android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />` in AndroidManifest.xml works for me. (`<uses-permission>` will only open the general battery optimization menu)
