### ISSUE TITLE
Statusbar still showing when activity should be fullscreen

### ISSUE THREAD

**Issue by jangerhard** [Karumi/Dexter#92]
### Expected behaviour
The activity should start and be full screen; no status bar or controls on the screen. 

### Actual behaviour
The activity starts and there is a visible status bar and controls. 

### Steps to reproduce
Have an activity set to be fullscreen, and put Dexter.Initialize and .setMultiplePermissions in onCreate() of the activity.

### Version of the library
2.3.1

**Comment by Serchinastico** [comment]
Hi @jangerhard 

We'll take a look as soon as we can 👍 

Thanks for reporting!

**Comment by jangerhard** [comment]
Somehow this fixed itself, and I have no idea how.. Sorry if this confused anyone.
