### ISSUE TITLE
How  to add Settings.ACTION_USAGE_ACCESS_SETTINGS

### ISSUE THREAD

**Issue by swa00** [Karumi/Dexter#96]
Hi guys,

thank you very much for your great work

How  to add
Settings.ACTION_USAGE_ACCESS_SETTINGS

Thx a lot

**Comment by Serchinastico** [comment]
Hi @swa00,

Sorry for the late response. 

I'm confused, `ACTION_USAGE_ACCESS_SETTINGS` is not a permission but an intent action. I'm not sure what are you trying to do but I just did a quick search in google and here is a couple links that might be useful for your case:
* http://stackoverflow.com/questions/39651734/how-to-close-action-usage-access-settings-intent-when-user-click-correct-target
* http://stackoverflow.com/questions/27215013/check-if-my-application-has-usage-access-enabled

**Comment by swa00** [comment]
Hi Serchinatico,
your solution is the "standard" way..  but not with a dialog via dexter with direct permission settings.
The user is confused to use the standard way (pressing twice the back key, after done)
