### ISSUE TITLE
not show custom dialog!

### ISSUE THREAD

**Issue by mahdimortazavi** [Karumi/Dexter#97]
### Expected behaviour
show custom dialog with title , massage , ...

### Actual behaviour

not show any custom dialog!!

### Steps to reproduce

![screenshot_1479633453](https://cloud.githubusercontent.com/assets/10667180/20461830/8a9866f6-af1f-11e6-8496-80ad278e1c56.png)

MainActivity 

        MultiplePermissionsListener dialogMultiplePermissionsListener =
                DialogOnAnyDeniedMultiplePermissionsListener.Builder
                        .withContext(this)
                        .withTitle("Camera & audio permission")
                        .withMessage("Both camera and audio permission are needed to take pictures of your cat")
                        .withButtonText(android.R.string.ok)
                        .withIcon(android.R.drawable.ic_input_add)
                        .build();
        Dexter.checkPermissions(dialogMultiplePermissionsListener, Manifest.permission.CAMERA, Manifest.permission.READ_CONTACTS, Manifest.permission.RECORD_AUDIO);
    

MyApplication Class

    @Override
    public void onCreate() {
        super.onCreate();
        Dexter.initialize(getApplicationContext());
    }

compileSdkVersion 25
    buildToolsVersion "25.0.0"
        minSdkVersion 17
        targetSdkVersion 25

### Version of the library

  compile 'com.karumi:dexter:2.3.1'

**Comment by Serchinastico** [comment]
Hi @mahdimortazavi 

The dialog you are trying to display should only be shown if the user rejects the permission once. That's called a rationale. 

The dialog in the screenshot is the native Android permission dialog and there is nothing anyone can do to avoid showing it, it's in the framework. I recommend you to read carefully the [section of our README](https://github.com/Karumi/Dexter#showing-a-rationale) that explains this a little more in depth.

Cheers and thanks for reporting!
