### ISSUE TITLE
Can I show the Snackbar only when the permission has been permanently denied

### ISSUE THREAD

**Issue by crocodile** [Karumi/Dexter#98]
### Expected behaviour (How Google Maps implemented permissions)
Can we avoid step 4 below? In other words I don't want to show the Snackbar until the user has permanently denied the permission.

### Actual behaviour (As it works in the sample app)
1. First time permission request
2. The Permission Dialog comes up (Without the 'Don't ask again' option)
3. User declines
4. Snackbar appears
5. Second time permission request 
6. The Permission Dialog comes up (With the 'Don't ask again' option)
7. User declines with 'Don't ask again' option checked
8. Snackbar appears
9. Third time Permission request (The Permission Dialog will no longer come up.)
10. Snackbar appears

### Version of the library
2.3.1
            
       if (Dexter.isRequestOngoing()) {
            return;
        }
        Dexter.checkPermission(new CompositePermissionListener(new PermissionListener() {

        `@SuppressWarnings("MissingPermission")

            @Override public void onPermissionGranted(PermissionGrantedResponse response) {
                  // Doing my stuff requiring the permission
           }

            @Override public void onPermissionDenied(PermissionDeniedResponse response) {
                if (response.isPermanentlyDenied()) {
                  // Can I enable/disable the snackbar from here???
                }
            }

            @Override public void onPermissionRationaleShouldBeShown(PermissionRequest permission, PermissionToken token) {
                token.continuePermissionRequest();
            }

        }, SnackbarOnDeniedPermissionListener.Builder
                .with(rootView, "Location needs to be enabled.")
                .withOpenSettingsButton("Settings").build()), Manifest.permission.ACCESS_FINE_LOCATION);`

Thanks!

**Comment by Serchinastico** [comment]
Hi @crocodile 

I'm afraid you can't modify `SnackbarOnDeniedPermissionListener` behavior. We just created that as an example and as an easy-to-plug example but it's not meant to be extended. You will have to create a permission listener of your own that shows the snackbar whenever you want.

Thanks for reporting!
