### ISSUE TITLE
file:// scheme is now not allowed to be attached with Intent on targetSdkVersion 24 (Android Nougat).

### ISSUE THREAD

**Issue by demilaram** [Karumi/Dexter#99]
### Expected behaviour
i am using your library to include images in my app, how ever it works fine for android up to android 6, when i use this on android 7 it crashes with FileUriExposedException, i use targetSdkVersion 24, and i think the problem is described [here](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en)

**Comment by Serchinastico** [comment]
Hi @demilaram 

The problem is not in Dexter, this library is only used to handle runtime permissions, not to pass/load/include images of any kind in any app.

I'd recommend you to read your code and see where are you passing a URL with the `file` scheme inside an intent.

Thanks for reporting.

**Comment by demilaram** [comment]
@Serchinastico thanks for your reply, i was not suppose to right this issue here, it was for a picking image library, which i use along with this library, i dont know how i ended up here :)
